name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Sync files via rsync
      run: |
        rsync -avz --delete --exclude '.git*' ./ root@pathcreator.ru:/var/www/www-root/data/www/site.pathcreator.ru

    - name: Restart server
      run: |
        ssh root@pathcreator.ru 'sudo systemctl restart your-service'
