# Имя рабочего процесса
name: Deploy to Server

# Определяет условия запуска рабочего процесса: на пуш в ветку main
on:
  push:
    branches:
      - main

jobs:
  # Задание с именем deploy, которое выполняется на виртуальной машине с Ubuntu
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Первый шаг: клонирование репозитория в виртуальную машину
      - name: Checkout repository
        uses: actions/checkout@v2

      # Настройка SSH для безопасного подключения к удаленному серверу
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     # Синхронизация файлов с удаленным сервером с использованием rsync
#      rsync: Это основная команда для синхронизации файлов и директорий между двумя местоположениями.
#
#      -a: Включает архивный режим. Он рекурсивно копирует файлы и сохраняет большинство атрибутов файлов (права доступа, временные метки и т.д.). Это аналогично использованию опций -rlptgoD.
#
#      -v: Включает подробный режим (verbose), что позволяет видеть подробную информацию о процессе копирования.
#
#      -z: Включает сжатие файлов во время передачи, что может уменьшить время передачи данных по сети.
#
#      --delete: Удаляет файлы в целевом каталоге, которые были удалены в исходном каталоге. Это обеспечивает синхронизацию содержимого обеих директорий.
#
#      --exclude '.git*': Исключает из синхронизации файлы и папки, имена которых начинаются с .git. Это полезно для исключения репозиториев Git и связанных файлов.
#
#      ./: Исходный каталог, из которого будут копироваться файлы. В данном случае это текущий каталог.
#
#      root@pathcreator.ru:/var/www/www-root/data/www/site.pathcreator.ru: Целевое местоположение на удаленном сервере. Это указывает, что файлы должны быть скопированы в директорию /var/www/www-root/data/www/site.pathcreator.ru на сервере pathcreator.ru под учетной записью пользователя root.
      - name: Sync files via rsync
        run: |
          rsync -avz --delete --exclude '.git*' ./ root@pathcreator.ru:/var/www/www-root/data/www/site.pathcreator.ru